site_name: AvatarSceneBrowserDoc
site_description: AvatarSceneBrowser插件文档
site_author: Cyn-thiatMt
site_url: https://cynth-mt.github.io/AvatarSceneBrowserDoc/
use_directory_urls: true

# repo_name: Cynth-Mt/AvatarSceneBrowserDoc
# repo_url: https://github.com/Cynth-Mt/AvatarSceneBrowserDoc
# edit_uri: edit/main/docs/

repo_url: https://x.com/CYTHIAM246
repo_name: Twitter

theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/twitter
  palette:
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy

plugins:
  - search:
      lang: zh
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 主页: index.md
  - 使用教程:  tutorial.md
  - 场景浏览: scene-browsing.md
  - 菜单结构: menu-structure.md
  - GUID批量更新工具: guid-batch-update-tool.md
  - 标签管理: tag-manager.md
  - 常见问题: faq.md
  - 更新日志: update-history.md

extra:
  generator: true

# Force rebuild - debug deployment 