site_name: AvatarSceneBrowserDoc
site_description: AvatarSceneBrowser插件文档
site_author: Cyn-thiatMt
site_url: https://cynth-mt.github.io/AvatarSceneBrowserDoc/
use_directory_urls: true

# repo_name: Cynth-Mt/AvatarSceneBrowserDoc
# repo_url: https://github.com/Cynth-Mt/AvatarSceneBrowserDoc
# edit_uri: edit/main/docs/

#repo_url: https://x.com/CYTHIAM246
#repo_name: Twitter

theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/twitter
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式

plugins:
  - search:
      lang:
        - zh
        - ja
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            主页: ホーム
            使用教程: 使用チュートリアル
            主窗口（截图预览）: メインウィンドウ（スクリーンショットプレビュー）
            菜单结构: メニュー構造
            GUID批量更新工具: GUID一括更新ツール
            标签管理工具: タグ管理ツール
            常见问题: よくある質問
            更新日志: 更新履歴
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - 主页: index.md
  - 使用教程:  tutorial.md
  - 主窗口（截图预览）: main-window.md
  - 菜单结构: menu-structure.md
  - --------:
      - GUID批量更新工具: guid-batch-update-tool.md
      - 标签管理工具: tag-manager.md
  - --------:
      - 常见问题: faq.md
      - 更新日志: update-history.md

extra:
  generator: true
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/CYTHIAM246

# Force rebuild - debug deployment 